
on: push

permissions: read-all

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.sdkman
          key: "${{ runner.os }}-sdkman-${{ hashFiles('.sdkmanrc') }}"
          restore-keys: "${{ runner.os }}-sdkman-"
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: "${{ runner.os }}-maven-"
      - run: curl -s "https://get.sdkman.io?rcupdate=false" | bash
      - run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk env install
          ./mvnw
